id: 9535614a9a13464398b732ee774a121f
initial_creation_type: ocr
source_metadata:
  volumes:
    edaaff9940e3484f99f25784064cec31:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: དེ་ཁོ་ན་ཉིད་གྲུབ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1349
      volume_number: 41
